export const SET_TOKEN_SUCCESS = 'SET_TOKEN_SUCCESS';
export const TWILIO_LOGOUT = 'TWILIO_LOGOUT';
export const HOST_AVAILABLE = 'HOST_AVAILABLE';
export const SET_MEETING_ROOM = 'SET_MEETING_ROOM';
